name: Docker Image CI (build, python dependencies test, push registry)

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "*.md" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "*.md" ]
       
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install Dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Get refs - this will be used as tags later on
      shell: bash
      run: |
        echo "::set-output name=sha12::$(echo ${GITHUB_SHA} | cut -c1-12)"
      id: getrefs
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rgriffogoes:$(date +%s)

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: "."
        file: "Dockerfile"
        push: true
        tags: |
          rgriffogoes/ad-mqtt:${{steps.getrefs.outputs.sha12}}, rgriffogoes/ad-mqtt:latest
